import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';

export async function POST(request: Request) {
    try {
        const body = await request.json();

        // 1. Generate Ticket ID
        const randomNum = Math.floor(10000 + Math.random() * 90000);
        const ticketId = `ORP5IC-${body.nationality === 'indian' ? 'IND' : 'INT'}-${randomNum}`;

        // 2. Auto-Tagging
        const tags = [];
        if (body.nationality === 'indian') tags.push('INDIAN'); else tags.push('FOREIGN');
        if (body.mode === 'virtual') tags.push('VIRTUAL'); else tags.push('PHYSICAL');
        if (body.membershipType === 'AIASA Member') tags.push('AIASA_MEMBER');

        // 3. Construct Data Object (JSONB)
        const registrationData = {
            ticket_number: ticketId,
            ...body,
            payment_status: 'paid', // Mock
            payment_mode: 'Mock Gateway',
            payment_date: new Date().toISOString(),
            tags: tags,
            submittedAt: new Date().toISOString()
        };

        // 4. Save to Supabase (using 'data' column)
        const { data, error } = await supabase
            .from('Registration')
            .insert({
                data: registrationData
                // id autogenerated
            })
            .select('id')
            .single();

        if (error) {
            console.error("Error saving registration:", error);
            throw error;
        }

        return NextResponse.json({ success: true, ticketId: ticketId });
    } catch (error: any) {
        console.error("Error saving registration:", error);
        return NextResponse.json({ error: 'Failed to save registration', details: error.message || error }, { status: 500 });
    }
}

export async function GET() {
    try {
        const { data, error } = await supabase
            .from('Registration')
            .select('*')
            .order('submittedAt', { ascending: false });

        if (error) throw error;

        // Flatten JSONB 'data' to top-level for frontend
        const flattened = data.map((row: any) => ({
            id: row.id,
            submittedAt: row.submittedAt,
            ...row.data
        }));

        return NextResponse.json(flattened);
    } catch (e) {
        console.error("Error fetching registrations:", e);
        return NextResponse.json([]);
    }
}
